const fs = require("fs");
// new file created
fs.writeFile(
  "readbyasync.txt",
  "this file is generated by Async method",
  (err) => {
    if (err) {
      console.log("err", err);
    }
    console.log("your file sucessfully created");
  }
);
console.log("try");

// edit previous file

fs.appendFile("readbyasy.txt", "hello world ahashahsjhjasassa", (err) => {
  if (err) {
    console.log("err", err);
  } else {
    console.log("file data updated sucessfully");
  }
});

// read data from file
// UTF-8 method is used for read data in string format
fs.readFile("readbyasync.txt", "UTF-8", (err, data) => {
  if (err) {
    console.log("err", err);
  } else {
    console.log("data", data);
  }
});
console.log("fs", fs);
